async function loadNews() {
  try {
    // Fetch the JSON file generated by the Python Action
    const response = await fetch('./data.json');
    const data = await response.json();

    // Example: Populating an NFL tile
    if (data.nfl) {
      const nflContainer = document.getElementById('nfl-feed');
      nflContainer.innerHTML = data.nfl.map(item => 
        `<li><a href="${item.link}" target="_blank">${item.title}</a></li>`
      ).join('');
    }
    
    // Repeat for other categories (nba, tech, etc.)
    // Or use a loop:
    Object.keys(data).forEach(category => {
        const el = document.getElementById(`${category}-feed`);
        if (el) {
            el.innerHTML = data[category].slice(0, 5).map(item => 
                `<li><a href="${item.link}">${item.title}</a></li>`
            ).join('');
        }
    });

  } catch (error) {
    console.error("Error loading the news data:", error);
  }
}

document.addEventListener('DOMContentLoaded', loadNews);
