'use strict';

/**
 * SysLog Frontend Logic
 * Fetches data from the local data.json (updated by GitHub Actions)
 * and Open-Meteo for live weather.
 */

const CONFIG = {
    // Maps the 'keys' in your data.json to the 'Labels' on your dashboard
    groups: [
        { id: 'nfl', label: 'NFL' },
        { id: 'nba', label: 'NBA' },
        { id: 'mlb', label: 'MLB' },
        { id: 'tech', label: 'TECH' },
        { id: 'cyber', label: 'CYBER' },
        { id: 'gaming', label: 'GAMING' },
        { id: 'space', label: 'SPACE' },
        { id: 'science', label: 'SCIENCE' }
    ],
    refreshRate: 30 * 60 * 1000 // Refresh news every 30 minutes
};

// --- 1. Weather Logic ---
async function updateWeather() {
    try {
        const geoRes = await fetch('https://ipapi.co/json/');
        const geo = await geoRes.json();
        
        const weatherUrl = `https://api.open-meteo.com/v1/forecast?latitude=${geo.latitude}&longitude=${geo.longitude}&current_weather=true&temperature_unit=fahrenheit&hourly=relative_humidity_2m`;
        const wRes = await fetch(weatherUrl);
        const w = await wRes.json();

        // Update Popup elements
        document.getElementById('w-temp').innerText = `${Math.round(w.current_weather.temperature)}°F`;
        document.getElementById('w-condition').innerText = `Code: ${w.current_weather.weathercode}`;
        document.getElementById('w-humidity').innerText = `${w.hourly.relative_humidity_2m[0]}%`;
        document.getElementById('w-wind').innerText = `${Math.round(w.current_weather.windspeed)} mph`;
        document.getElementById('w-loc').innerText = `📍 ${geo.city}, ${geo.region_code}`;
        
    } catch (err) {
        console.warn("Weather sync failed:", err);
    }
}

// --- 2. News Logic ---
async function loadNews() {
    const wall = document.getElementById('wall');
    
    try {
        // Fetch the JSON file generated by your Python Scraper
        const response = await fetch('./data.json?t=' + Date.now()); // Query string prevents browser caching
        const data = await response.json();

        // Clear the "Initializing" status
        wall.innerHTML = '';

        CONFIG.groups.forEach(group => {
            if (!data[group.id] || data[group.id].length === 0) return;

            const row = document.createElement('div');
            row.className = 'row';

            // Create the infinite scroll track
            // We double the data list to ensure the animation loops seamlessly
            const items = [...data[group.id], ...data[group.id]];
            
            const trackHtml = items.map(item => `
                <a href="${item.link}" target="_blank" class="item">
                    <span class="source-tag">[${group.id.toUpperCase()}]</span>
                    ${item.title}
                </a>
            `).join('');

            row.innerHTML = `
                <div class="label">${group.label}</div>
                <div class="track-wrapper">
                    <div class="track">${trackHtml}</div>
                </div>
            `;

            wall.appendChild(row);
        });

    } catch (error) {
        console.error("Critical error loading news stream:", error);
        wall.innerHTML = `<div class="status">STREAM_OFFLINE: Run GitHub Action to generate data.json</div>`;
    }
}

// --- 3. UI Interactions ---
function setupInteractions() {
    const weatherBtn = document.getElementById('weather-btn');
    const weatherPopup = document.getElementById('weather-popup');

    if (weatherBtn && weatherPopup) {
        weatherBtn.addEventListener('click', () => weatherPopup.classList.toggle('active'));
        
        // Close popup when clicking outside
        document.addEventListener('click', (e) => {
            if (!e.target.closest('.weather-button') && !e.target.closest('.weather-popup')) {
                weatherPopup.classList.remove('active');
            }
        });
    }
}

// --- Initialize ---
document.addEventListener('DOMContentLoaded', () => {
    setupInteractions();
    updateWeather();
    loadNews();

    // Set auto-refresh
    setInterval(loadNews, CONFIG.refreshRate);
    setInterval(updateWeather, CONFIG.refreshRate);
});
